import User from "../models/User.js";
import { pgPool } from "../config/db.js";

export const registerUser = async (req, res) => {
  const { name, email, password, rollNumber } = req.body;

  try {
    // Phase 1: Save Profile to MongoDB
    const mongoUser = new User({ name, email, password, rollNumber });
    const savedUser = await mongoUser.save();

    // Phase 2: Initialize Social Stats in PostgreSQL
    // We use the ID generated by MongoDB to link the two
    await pgPool.query(
      "INSERT INTO users_social (user_id) VALUES ($1)",
      [savedUser._id.toString()]
    );

    res.status(201).json({ 
      message: "Student account created successfully across platform!",
      userId: savedUser._id 
    });
  } catch (error) {
    console.error("Registration Sync Error:", error);
    res.status(500).json({ error: "Could not complete registration" });
  }
};